### PR TITLE
CI

### LINKED ISSUE #108: CI for testing Julia scripts and environment
I will be great to have this feature for the final version of the paper, so we check the `Project.toml` and all the scrips run and this is stable over time in this repo. @avik-pal would you have any time for this?

### PR DESCRIPTION
**Pull request by avik-pal**
Fixes #108

### CODE REVIEW

**Comment by avik-pal** [comment]
@ChrisRackauckas did something change in solution indexing (yesterday?) https://github.com/ODINN-SciML/DiffEqSensitivity-Review/actions/runs/9492247292/job/26159059628?pr=112#step:5:1412

All the scripts were working locally just yesterday for me.

**Comment by avik-pal** [comment]
Ok Zygote with ODESolution seems pretty much broken right now :(

**Comment by facusapienza21** [comment]
@avik-pal any idea of what is causing the error? Should I wait to integrate this PR? 

I ran all in local today and worked perfectly well.

**Comment by ChrisRackauckas** [comment]
One of the big changes around symbolic indexing seems to have broken master. We're doing a hotfix:

* https://github.com/SciML/SciMLBase.jl/pull/716

**Comment by ChrisRackauckas** [comment]
Retrigger

**Pull request merged**
